### ISSUE TITLE
Support additional test credit card numbers?

### ISSUE THREAD

**Issue by theogravity** [3rd-Eden/creditcard#3]
Some of the numbers listed via https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm

will return `validCardNumber` with a false value.

**Comment by 3rd-Eden** [comment]
Accepting pull requests for this :)

**Comment by theogravity** [comment]
Awesome, will do :)

**Comment by weisjohn** [comment]
@theogravity can you mention which ones?
